### ISSUE TITLE
Client error: POST

### ISSUE THREAD

**Issue by whydea** [giovaness30/essystem-boleto-getnet#1]
Olá, cara, estou tentando utilizar seu plugin no projeto de um cliente e está acusando erros, vou mandar em anexo.
Gostaria de saber a solução para poder fazer a utilização, muito obrigado por ter desenvolvido esse plugin.

Erro no sandbox:
![sandboxError](https://user-images.githubusercontent.com/63257972/105499598-7dcc5d00-5ca0-11eb-800b-af45d77aee5f.PNG)

Erro em prod:
![prodError](https://user-images.githubusercontent.com/63257972/105499636-8a50b580-5ca0-11eb-8881-ce32ee1be224.PNG)

**Comment by giovaness30** [comment]
Ola Beleza?
O plugin foi testando em modo SandBox (100% retorno funcional) 401 seria um retorno de não autorizado, talvez verificar sua chave client_id e client_secret.
Sobre já em produção, Verificando com Pessoal da Getnet, me passaram que precisa ser habilitado pela agencia do cliente a função de XML por boletos.

**Comment by whydea** [comment]
Testando em modo sandbox, conforme conversamos no linkedin, funcionou corretamente.
